/*

 SCREENTITLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Mihai4544\Desktop\Gameboy\gbtd22\pongScreenTitle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define screenTitleMapWidth 20
#define screenTitleMapHeight 18
#define screenTitleMapBank 0

extern unsigned char screenTitleMap[];

/* End of SCREENTITLEMAP.H */
